// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// qloop_numeric
NumericVector qloop_numeric(NumericVector queue_times, NumericVector times, NumericVector service, NumericVector output);
RcppExport SEXP queuecomputer_qloop_numeric(SEXP queue_timesSEXP, SEXP timesSEXP, SEXP serviceSEXP, SEXP outputSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type queue_times(queue_timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type times(timesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type service(serviceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type output(outputSEXP);
    rcpp_result_gen = Rcpp::wrap(qloop_numeric(queue_times, times, service, output));
    return rcpp_result_gen;
END_RCPP
}
