# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qloop_numeric <- function(queue_times, times, service, output) {
    .Call('queuecomputer_qloop_numeric', PACKAGE = 'queuecomputer', queue_times, times, service, output)
}

qloop_quick_q <- function(queue_times, times, service, output, x, y) {
    .Call('queuecomputer_qloop_quick_q', PACKAGE = 'queuecomputer', queue_times, times, service, output, x, y)
}

