# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qloop_numeric <- function(times, service, output, n_servers) {
    .Call('queuecomputer_qloop_numeric', PACKAGE = 'queuecomputer', times, service, output, n_servers)
}

qloop_quick_q_test <- function(times, service, x, y) {
    .Call('queuecomputer_qloop_quick_q_test', PACKAGE = 'queuecomputer', times, service, x, y)
}

qloop_quick_q <- function(Infty, times, service, output, x, y) {
    .Call('queuecomputer_qloop_quick_q', PACKAGE = 'queuecomputer', Infty, times, service, output, x, y)
}

test <- function(input) {
    .Call('queuecomputer_test', PACKAGE = 'queuecomputer', input)
}

